services:
  server:
    platform: linux/amd64
    image: jenkins/jenkins:2.385-slim
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  agent:
    platform: linux/amd64
    image: jenkins-agent
    build:
      context: .
      dockerfile: agent/Dockerfile
      args:
        platform: linux/amd64
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 ... jenkins
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1000M
    memswap_limit: 1000M
volumes:
  jenkins_home:
    external: true
    name: jenkins_home