---

vault:
  addr: https://keeper.example.com
  namespace: projectops-infra/dev
  secretpath: ops/harness/ei-stable
  secretmount: secret
  timeout: 10

manifest:
  url: https://maven.example.com/artifactory/symphony-group/com/example/vms/manifest
  timeout: 10
  name: stage1-stable
  component: installer-manifest
  regex: project-manifest.yml
  tmpdir: files
  version: latest
  keys:
    - administrationservice_version
    - consumeservice_version
    - orchestrationservice_version
    - notificationservice_version
    - manageservice_version
    - monitorservice_version
    - billingservice_version
    - workflowservice_version
    - auditingservice_version
    - templateservice_version
    - slmservice_version
    - incidentservice_version
    - alertservice_version
    - ipamservice_version
    - vulnerabilityservice_version
    - licensingservice_version
    - changemanagementservice_version
    - usermanagementgoservice_version
    - authservice_version
    - webhookservice_version
    - apimanageservice_version
    - dashboardservice_version
    - secretsservice_version
    - apigatewayservice_version

harness:
  url: https://app.harness.io/gateway/pipeline/api/inputSets 
  org: ORG
  timeout: 10
